### ISSUE TITLE
No values for Roll/Pitch in Scratch

### ISSUE THREAD

**Issue by SAODTHEKING** [RLBot/RLBotScratchInterface#1]
First of all thank you so much for doing this.

i was just wondering if you can add Roll/Pitch values so we can know if the bot is flipped.
and it will help so much in making bots fly!

Thank you!

**Comment by dtracers** [comment]
There are roll and pitch values.

What version of the framework are you using?
Might be easier to talk on the discord

**Comment by SAODTHEKING** [comment]
Im asking for a Roll/Pitch value reader block on the scratch.rlbot.org editor

i followed the instructions and downloaded python like an hour ago

im pretty sure im using the latest version

send discord link thx

**Comment by dtracers** [comment]
The discord link is listed on the github on the readme

Here is another one:
https://discord.gg/W37mPd

**Comment by tarehart** [comment]
I'll be adding these soon!

**Comment by SAODTHEKING** [comment]
Thank you!

**Comment by SAODTHEKING** [comment]
A boost value also would be great!

**Comment by tarehart** [comment]
Added pitch, roll, and boost value. Sorry it took forever!
